(base) ]0;~/nlp-chatbox-demo/app[01;34m~/nlp-chatbox-demo/app[00m$ python3 -m main
Try to open

    https://cocalc13.ai-camp.dev/3df115f7-b265-4ae7-8859-4c52553a6d3a/port/12346/


 * Serving Flask app "main" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
Traceback (most recent call last):
  File "/projects/3df115f7-b265-4ae7-8859-4c52553a6d3a/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/projects/3df115f7-b265-4ae7-8859-4c52553a6d3a/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/projects/3df115f7-b265-4ae7-8859-4c52553a6d3a/nlp-chatbox-demo/app/main.py", line 106, in <module>
    app.run(host = '0.0.0.0', port=port, debug=True)
  File "/projects/3df115f7-b265-4ae7-8859-4c52553a6d3a/miniconda3/lib/python3.9/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/projects/3df115f7-b265-4ae7-8859-4c52553a6d3a/miniconda3/lib/python3.9/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
(base) ]0;~/nlp-chatbox-demo/app[01;34m~/nlp-chatbox-demo/app[00m$ 